export const analise = [{
    "ROWID": 1,
    "GRUANALI": 765,
    "CODANALI" : 30,
    "DESCANALI" : "Proteína",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "PB",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 2,
    "GRUANALI": 765,
    "CODANALI" : 36,
    "DESCANALI" : "Lipídios",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "LIPIDIOS",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 3,
    "GRUANALI": 765,
    "CODANALI" : 50,
    "DESCANALI" : "Umidade e Voláteis",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "UMD",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 4,
    "GRUANALI": 765,
    "CODANALI" : 509,
    "DESCANALI" : "Teor de ossos",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "TEOSS",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 5,
    "GRUANALI": 765,
    "CODANALI" : 79,
    "DESCANALI" : "Composição Centesimal",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "CO_CENT",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  },{
    "ROWID": 6,   
    "GRUANALI":338,
    "CODANALI" : 5,
    "DESCANALI" : "Salmonella spp",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "SALM",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "C",
    "CONSTIPOANALI" : 502
}, {
    "ROWID": 7,
    "GRUANALI":338,
    "CODANALI" : 1157,
    "DESCANALI" : "Temperatura de recebimento",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "TR",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
},{
    "ROWID": 8,
    "GRUANALI":339,
    "CODANALI" : 9,
    "DESCANALI" : "Enterobactérias",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "EB",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 9,
    "GRUANALI":339,
    "CODANALI" : 1157,
    "DESCANALI" : "Temperatura de recebimento",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "TR",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "S",
    "CONSTIPOANALI" : 502
  }, {
    "ROWID": 10,
    "GRUANALI":339,
    "CODANALI" : 81,
    "DESCANALI" : "Bactérias mesófilas aeróbias viáveis",
    "MINIMO" : null,
    "MAXIMO" : null,
    "ABREVIACAO" : "CPP",
    "NCOPIATEMP" : 1,
    "PRECOANA" : null,
    "TIPORELAC" : "F",
    "CONSTIPOANALI" : 502
  }
]